services:
  - type: web
    name: docflow-backend
    runtime: node
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y graphicsmagick
      npm install
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "18"